INFO:nt:NetworkTables 2017.0.4 initialized in client mode
Traceback (most recent call last):
  File "nt_client.py", line 40, in <module>
    for frame in camera.capture_continuous(rawCapture, format="bgr", use_video_port=True):
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/picamera/camera.py", line 1672, in capture_continuous
    encoder.close()
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/picamera/encoders.py", line 453, in close
    self.stop()
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/picamera/encoders.py", line 441, in stop
    self._close_output()
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/picamera/encoders.py", line 367, in _close_output
    output.flush()
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/picamera/array.py", line 224, in flush
    self.array = bytes_to_rgb(self.getvalue(), self.size or self.camera.resolution)
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/picamera/array.py", line 113, in bytes_to_rgb
    'Incorrect buffer length for resolution %dx%d' % (width, height))
picamera.exc.PiCameraValueError: Incorrect buffer length for resolution 640x480
Exception in thread nt-dispatch-thread (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/ntcore/dispatcher.py", line 260, in _dispatchThreadMain
  File "/home/pi/.virtualenvs/cv/local/lib/python2.7/site-packages/ntcore/support/compat.py", line 83, in wait_for
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
